FROM centos:7

ENV prueba 1234

RUN useradd daniel

# docker run -dti -e "prueba1=4321" --name environment env
# -dti =
# -d is for background task
# -t is for terminal
# -i is for interactive
# -e is for environment Variable and indicated between ""
# --name is for naming on docker
# env is the image used