version: '3'
services:
  web:
    container_name: nginx2
    ports:
      - "8081:80"
    volumes: 
      - "/Users/nikedanz/codebase/docker/docker-images/docker-compose/html:/usr/share/nginx/html"
    image: nginx